// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pcie_read_req_mux,hls_ip_2017_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.806750,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=80,HLS_SYN_LUT=665}" *)

module pcie_read_req_mux (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
ap_continue,
        ap_idle,
        ap_ready,
        pcie_read_req_V_num_din,
        pcie_read_req_V_num_full_n,
        pcie_read_req_V_num_write,
        pcie_read_req_V_addr_din,
        pcie_read_req_V_addr_full_n,
        pcie_read_req_V_addr_write,
        hw_pcie_read_req_V_num_dout,
        hw_pcie_read_req_V_num_empty_n,
        hw_pcie_read_req_V_num_read,
        hw_pcie_read_req_V_addr_dout,
        hw_pcie_read_req_V_addr_empty_n,
        hw_pcie_read_req_V_addr_read,
        cosim_dramA_read_req_V_num_dout,
        cosim_dramA_read_req_V_num_empty_n,
        cosim_dramA_read_req_V_num_read,
        cosim_dramA_read_req_V_addr_dout,
        cosim_dramA_read_req_V_addr_empty_n,
        cosim_dramA_read_req_V_addr_read,
        cosim_dramB_read_req_V_num_dout,
        cosim_dramB_read_req_V_num_empty_n,
        cosim_dramB_read_req_V_num_read,
        cosim_dramB_read_req_V_addr_dout,
        cosim_dramB_read_req_V_addr_empty_n,
        cosim_dramB_read_req_V_addr_read,
        cosim_dramC_read_req_V_num_dout,
        cosim_dramC_read_req_V_num_empty_n,
        cosim_dramC_read_req_V_num_read,
        cosim_dramC_read_req_V_addr_dout,
        cosim_dramC_read_req_V_addr_empty_n,
        cosim_dramC_read_req_V_addr_read,
        cosim_dramD_read_req_V_num_dout,
        cosim_dramD_read_req_V_num_empty_n,
        cosim_dramD_read_req_V_num_read,
        cosim_dramD_read_req_V_addr_dout,
        cosim_dramD_read_req_V_addr_empty_n,
        cosim_dramD_read_req_V_addr_read,
        pcie_read_multiplexer_write_context_V_din,
        pcie_read_multiplexer_write_context_V_full_n,
        pcie_read_multiplexer_write_context_V_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output ap_ready; output ap_continue;
output  [7:0] pcie_read_req_V_num_din;
input   pcie_read_req_V_num_full_n;
output   pcie_read_req_V_num_write;
output  [63:0] pcie_read_req_V_addr_din;
input   pcie_read_req_V_addr_full_n;
output   pcie_read_req_V_addr_write;
input  [7:0] hw_pcie_read_req_V_num_dout;
input   hw_pcie_read_req_V_num_empty_n;
output   hw_pcie_read_req_V_num_read;
input  [63:0] hw_pcie_read_req_V_addr_dout;
input   hw_pcie_read_req_V_addr_empty_n;
output   hw_pcie_read_req_V_addr_read;
input  [7:0] cosim_dramA_read_req_V_num_dout;
input   cosim_dramA_read_req_V_num_empty_n;
output   cosim_dramA_read_req_V_num_read;
input  [63:0] cosim_dramA_read_req_V_addr_dout;
input   cosim_dramA_read_req_V_addr_empty_n;
output   cosim_dramA_read_req_V_addr_read;
input  [7:0] cosim_dramB_read_req_V_num_dout;
input   cosim_dramB_read_req_V_num_empty_n;
output   cosim_dramB_read_req_V_num_read;
input  [63:0] cosim_dramB_read_req_V_addr_dout;
input   cosim_dramB_read_req_V_addr_empty_n;
output   cosim_dramB_read_req_V_addr_read;
input  [7:0] cosim_dramC_read_req_V_num_dout;
input   cosim_dramC_read_req_V_num_empty_n;
output   cosim_dramC_read_req_V_num_read;
input  [63:0] cosim_dramC_read_req_V_addr_dout;
input   cosim_dramC_read_req_V_addr_empty_n;
output   cosim_dramC_read_req_V_addr_read;
input  [7:0] cosim_dramD_read_req_V_num_dout;
input   cosim_dramD_read_req_V_num_empty_n;
output   cosim_dramD_read_req_V_num_read;
input  [63:0] cosim_dramD_read_req_V_addr_dout;
input   cosim_dramD_read_req_V_addr_empty_n;
output   cosim_dramD_read_req_V_addr_read;
output  [7:0] pcie_read_multiplexer_write_context_V_din;
input   pcie_read_multiplexer_write_context_V_full_n;
output   pcie_read_multiplexer_write_context_V_write;

reg ap_idle;
reg pcie_read_multiplexer_write_context_V_write;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    pcie_read_req_V_num_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_9_reg_545;
reg    pcie_read_req_V_addr_blk_n;
reg    pcie_read_multiplexer_write_context_V_blk_n;
reg   [2:0] flag_4_reg_303;
wire   [0:0] empty_n_5_fu_323_p1;
wire    ap_block_state2_pp0_stage0_iter0;
wire    pcie_read_req_V_num1_status;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] empty_n_6_fu_335_p1;
wire   [0:0] empty_n_7_fu_347_p1;
wire   [0:0] empty_n_8_fu_359_p1;
wire   [0:0] tmp_9_fu_488_p2;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [2:0] ap_phi_precharge_reg_pp0_iter0_flag_4_reg_303;
reg   [2:0] flag_4_phi_fu_306_p10;
wire   [2:0] flag_fu_411_p3;
reg    hw_pcie_read_req_V_num0_update;
wire   [0:0] empty_n_nbread_fu_246_p3_0;
reg    cosim_dramA_read_req_V_num0_update;
wire   [0:0] empty_n_1_nbread_fu_254_p3_0;
reg    cosim_dramB_read_req_V_num0_update;
wire   [0:0] empty_n_2_nbread_fu_262_p3_0;
reg    cosim_dramC_read_req_V_num0_update;
wire   [0:0] empty_n_3_nbread_fu_270_p3_0;
reg    cosim_dramD_read_req_V_num0_update;
wire   [0:0] empty_n_4_nbread_fu_278_p3_0;
reg    pcie_read_req_V_num1_update;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] tmp_num_fu_238;
wire   [7:0] read_req_num_4_fu_403_p3;
reg   [63:0] tmp_addr_fu_242;
wire   [63:0] read_req_addr_4_fu_395_p3;
wire   [63:0] read_req_addr_2_fu_430_p2;
wire   [63:0] read_req_addr_1_fu_446_p2;
wire   [63:0] read_req_addr_fu_462_p2;
wire   [63:0] read_req_addr_3_fu_389_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_146;
reg    ap_condition_151;
reg    ap_condition_156;
reg    ap_condition_142;
reg    ap_condition_136;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_subdone == 1'b0)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_136 == 1'b1)) begin
        if ((empty_n_5_fu_323_p1 == 1'd1)) begin
            flag_4_reg_303 <= 3'd1;
        end else if ((ap_condition_156 == 1'b1)) begin
            flag_4_reg_303 <= flag_fu_411_p3;
        end else if ((ap_condition_151 == 1'b1)) begin
            flag_4_reg_303 <= 3'd4;
        end else if ((ap_condition_146 == 1'b1)) begin
            flag_4_reg_303 <= 3'd3;
        end else if (((1'd0 == empty_n_5_fu_323_p1) & (empty_n_6_fu_335_p1 == 1'd1))) begin
            flag_4_reg_303 <= 3'd2;
        end else if ((1'b1 == 1'b1)) begin
            flag_4_reg_303 <= ap_phi_precharge_reg_pp0_iter0_flag_4_reg_303;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_136 == 1'b1)) begin
        if ((empty_n_5_fu_323_p1 == 1'd1)) begin
            tmp_addr_fu_242 <= hw_pcie_read_req_V_addr_dout;
        end else if (((1'd0 == empty_n_5_fu_323_p1) & (empty_n_6_fu_335_p1 == 1'd1))) begin
            tmp_addr_fu_242 <= read_req_addr_fu_462_p2;
        end else if ((ap_condition_146 == 1'b1)) begin
            tmp_addr_fu_242 <= read_req_addr_1_fu_446_p2;
        end else if ((ap_condition_151 == 1'b1)) begin
            tmp_addr_fu_242 <= read_req_addr_2_fu_430_p2;
        end else if ((ap_condition_156 == 1'b1)) begin
            tmp_addr_fu_242 <= read_req_addr_4_fu_395_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_136 == 1'b1)) begin
        if ((empty_n_5_fu_323_p1 == 1'd1)) begin
            tmp_num_fu_238 <= hw_pcie_read_req_V_num_dout;
        end else if (((1'd0 == empty_n_5_fu_323_p1) & (empty_n_6_fu_335_p1 == 1'd1))) begin
            tmp_num_fu_238 <= cosim_dramA_read_req_V_num_dout;
        end else if ((ap_condition_146 == 1'b1)) begin
            tmp_num_fu_238 <= cosim_dramB_read_req_V_num_dout;
        end else if ((ap_condition_151 == 1'b1)) begin
            tmp_num_fu_238 <= cosim_dramC_read_req_V_num_dout;
        end else if ((ap_condition_156 == 1'b1)) begin
            tmp_num_fu_238 <= read_req_num_4_fu_403_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        tmp_9_reg_545 <= tmp_9_fu_488_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd0 == empty_n_5_fu_323_p1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == (cosim_dramA_read_req_V_num_empty_n & cosim_dramA_read_req_V_addr_empty_n)))) begin
        cosim_dramA_read_req_V_num0_update = 1'b1;
    end else begin
        cosim_dramA_read_req_V_num0_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd0 == empty_n_5_fu_323_p1) & (1'd0 == empty_n_6_fu_335_p1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == (cosim_dramB_read_req_V_num_empty_n & cosim_dramB_read_req_V_addr_empty_n)))) begin
        cosim_dramB_read_req_V_num0_update = 1'b1;
    end else begin
        cosim_dramB_read_req_V_num0_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd0 == empty_n_5_fu_323_p1) & (1'd0 == empty_n_6_fu_335_p1) & (1'd0 == empty_n_7_fu_347_p1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == (cosim_dramC_read_req_V_num_empty_n & cosim_dramC_read_req_V_addr_empty_n)))) begin
        cosim_dramC_read_req_V_num0_update = 1'b1;
    end else begin
        cosim_dramC_read_req_V_num0_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'd0 == empty_n_5_fu_323_p1) & (1'd0 == empty_n_6_fu_335_p1) & (1'd0 == empty_n_7_fu_347_p1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == empty_n_8_fu_359_p1) & (1'b1 == (cosim_dramD_read_req_V_num_empty_n & cosim_dramD_read_req_V_addr_empty_n)))) begin
        cosim_dramD_read_req_V_num0_update = 1'b1;
    end else begin
        cosim_dramD_read_req_V_num0_update = 1'b0;
    end
end

always @ (*) begin
    if ((ap_condition_142 == 1'b1)) begin
        if ((empty_n_5_fu_323_p1 == 1'd1)) begin
            flag_4_phi_fu_306_p10 = 3'd1;
        end else if ((ap_condition_156 == 1'b1)) begin
            flag_4_phi_fu_306_p10 = flag_fu_411_p3;
        end else if ((ap_condition_151 == 1'b1)) begin
            flag_4_phi_fu_306_p10 = 3'd4;
        end else if ((ap_condition_146 == 1'b1)) begin
            flag_4_phi_fu_306_p10 = 3'd3;
        end else if (((1'd0 == empty_n_5_fu_323_p1) & (empty_n_6_fu_335_p1 == 1'd1))) begin
            flag_4_phi_fu_306_p10 = 3'd2;
        end else begin
            flag_4_phi_fu_306_p10 = ap_phi_precharge_reg_pp0_iter0_flag_4_reg_303;
        end
    end else begin
        flag_4_phi_fu_306_p10 = ap_phi_precharge_reg_pp0_iter0_flag_4_reg_303;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == (hw_pcie_read_req_V_num_empty_n & hw_pcie_read_req_V_addr_empty_n)))) begin
        hw_pcie_read_req_V_num0_update = 1'b1;
    end else begin
        hw_pcie_read_req_V_num0_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0 == 1'b0) & (tmp_9_reg_545 == 1'd0))) begin
        pcie_read_multiplexer_write_context_V_blk_n = pcie_read_multiplexer_write_context_V_full_n;
    end else begin
        pcie_read_multiplexer_write_context_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (tmp_9_reg_545 == 1'd0) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        pcie_read_multiplexer_write_context_V_write = 1'b1;
    end else begin
        pcie_read_multiplexer_write_context_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0 == 1'b0) & (tmp_9_reg_545 == 1'd0))) begin
        pcie_read_req_V_addr_blk_n = pcie_read_req_V_addr_full_n;
    end else begin
        pcie_read_req_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (tmp_9_reg_545 == 1'd0) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        pcie_read_req_V_num1_update = 1'b1;
    end else begin
        pcie_read_req_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0 == 1'b0) & (tmp_9_reg_545 == 1'd0))) begin
        pcie_read_req_V_num_blk_n = pcie_read_req_V_num_full_n;
    end else begin
        pcie_read_req_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((1'b1 == ap_enable_reg_pp0_iter1) & (((tmp_9_reg_545 == 1'd0) & (1'b0 == pcie_read_req_V_num1_status)) | ((tmp_9_reg_545 == 1'd0) & (1'b0 == pcie_read_multiplexer_write_context_V_full_n))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((1'b1 == ap_enable_reg_pp0_iter1) & (((tmp_9_reg_545 == 1'd0) & (1'b0 == pcie_read_req_V_num1_status)) | ((tmp_9_reg_545 == 1'd0) & (1'b0 == pcie_read_multiplexer_write_context_V_full_n))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b1 == ap_enable_reg_pp0_iter1) & (((tmp_9_reg_545 == 1'd0) & (1'b0 == pcie_read_req_V_num1_status)) | ((tmp_9_reg_545 == 1'd0) & (1'b0 == pcie_read_multiplexer_write_context_V_full_n))));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((tmp_9_reg_545 == 1'd0) & (1'b0 == pcie_read_req_V_num1_status)) | ((tmp_9_reg_545 == 1'd0) & (1'b0 == pcie_read_multiplexer_write_context_V_full_n)));
end

always @ (*) begin
    ap_condition_136 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0));
end

always @ (*) begin
    ap_condition_142 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0));
end

always @ (*) begin
    ap_condition_146 = ((1'd0 == empty_n_5_fu_323_p1) & (1'd0 == empty_n_6_fu_335_p1) & (empty_n_7_fu_347_p1 == 1'd1));
end

always @ (*) begin
    ap_condition_151 = ((1'd0 == empty_n_5_fu_323_p1) & (1'd0 == empty_n_6_fu_335_p1) & (1'd0 == empty_n_7_fu_347_p1) & (empty_n_8_fu_359_p1 == 1'd1));
end

always @ (*) begin
    ap_condition_156 = ((1'd0 == empty_n_5_fu_323_p1) & (1'd0 == empty_n_6_fu_335_p1) & (1'd0 == empty_n_7_fu_347_p1) & (1'd0 == empty_n_8_fu_359_p1));
end

assign ap_done = 1'b0;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_precharge_reg_pp0_iter0_flag_4_reg_303 = 'bx;

assign ap_ready = 1'b0;

assign cosim_dramA_read_req_V_addr_read = cosim_dramA_read_req_V_num0_update;

assign cosim_dramA_read_req_V_num_read = cosim_dramA_read_req_V_num0_update;

assign cosim_dramB_read_req_V_addr_read = cosim_dramB_read_req_V_num0_update;

assign cosim_dramB_read_req_V_num_read = cosim_dramB_read_req_V_num0_update;

assign cosim_dramC_read_req_V_addr_read = cosim_dramC_read_req_V_num0_update;

assign cosim_dramC_read_req_V_num_read = cosim_dramC_read_req_V_num0_update;

assign cosim_dramD_read_req_V_addr_read = cosim_dramD_read_req_V_num0_update;

assign cosim_dramD_read_req_V_num_read = cosim_dramD_read_req_V_num0_update;

assign empty_n_1_nbread_fu_254_p3_0 = (cosim_dramA_read_req_V_num_empty_n & cosim_dramA_read_req_V_addr_empty_n);

assign empty_n_2_nbread_fu_262_p3_0 = (cosim_dramB_read_req_V_num_empty_n & cosim_dramB_read_req_V_addr_empty_n);

assign empty_n_3_nbread_fu_270_p3_0 = (cosim_dramC_read_req_V_num_empty_n & cosim_dramC_read_req_V_addr_empty_n);

assign empty_n_4_nbread_fu_278_p3_0 = (cosim_dramD_read_req_V_num_empty_n & cosim_dramD_read_req_V_addr_empty_n);

assign empty_n_5_fu_323_p1 = empty_n_nbread_fu_246_p3_0;

assign empty_n_6_fu_335_p1 = empty_n_1_nbread_fu_254_p3_0;

assign empty_n_7_fu_347_p1 = empty_n_2_nbread_fu_262_p3_0;

assign empty_n_8_fu_359_p1 = empty_n_3_nbread_fu_270_p3_0;

assign empty_n_nbread_fu_246_p3_0 = (hw_pcie_read_req_V_num_empty_n & hw_pcie_read_req_V_addr_empty_n);

assign flag_fu_411_p3 = ((empty_n_4_nbread_fu_278_p3_0[0:0] === 1'b1) ? 3'd5 : 3'd0);

assign hw_pcie_read_req_V_addr_read = hw_pcie_read_req_V_num0_update;

assign hw_pcie_read_req_V_num_read = hw_pcie_read_req_V_num0_update;

assign pcie_read_multiplexer_write_context_V_din = flag_4_reg_303;

assign pcie_read_req_V_addr_din = tmp_addr_fu_242;

assign pcie_read_req_V_addr_write = pcie_read_req_V_num1_update;

assign pcie_read_req_V_num1_status = (pcie_read_req_V_num_full_n & pcie_read_req_V_addr_full_n);

assign pcie_read_req_V_num_din = tmp_num_fu_238;

assign pcie_read_req_V_num_write = pcie_read_req_V_num1_update;

assign read_req_addr_1_fu_446_p2 = (cosim_dramB_read_req_V_addr_dout + 64'd34359738368);

assign read_req_addr_2_fu_430_p2 = (cosim_dramC_read_req_V_addr_dout + 64'd51539607552);

assign read_req_addr_3_fu_389_p2 = (cosim_dramD_read_req_V_addr_dout + 64'd68719476736);

assign read_req_addr_4_fu_395_p3 = ((empty_n_4_nbread_fu_278_p3_0[0:0] === 1'b1) ? read_req_addr_3_fu_389_p2 : tmp_addr_fu_242);

assign read_req_addr_fu_462_p2 = (cosim_dramA_read_req_V_addr_dout + 64'd17179869184);

assign read_req_num_4_fu_403_p3 = ((empty_n_4_nbread_fu_278_p3_0[0:0] === 1'b1) ? cosim_dramD_read_req_V_num_dout : tmp_num_fu_238);

assign tmp_9_fu_488_p2 = ((flag_4_phi_fu_306_p10 == 3'd0) ? 1'b1 : 1'b0);

endmodule //pcie_read_req_mux
